# tasks file
---

- import_tasks: "{{ role_path }}/tasks/setup_install.yml"
  when: ms_r_enabled|bool
  tags:
    - setup-all
    - setup-ms-r
    - setup-ms-develall

- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: not ms_r_enabled|bool
  tags:
    - setup-all
    - setup-ms-r
    - setup-ms-develall


